title: "Blog for L"
author: "Jason"
description: "Major in Finance, Quant, Data Science"
keyword: "刘笠, liuli, ll1735, liuli1735"
baseurl: ""
url: "http://liuli.me"

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
highlighter: pygments
permalink: /:year/:month/:day/:title.html
paginate: 5

# SNS settings
#weibo_username:  ll1735
#douban_username:  ll1735
#zhihu_username:   ll1735
#facebook_username:  ll1735
#twitter_username:  ll1735
#linkedin_username:  ll1735
#github_username:  liuli1735

# Disqus settings
disqus_username: liuli1735
# Duoshuo settings
#duoshuo_username: ll1735
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                    # set to false if you want to use Comment without Sharing

# Analytics settings
# Baidu Analytics
baidu_track_id: 98dfb384afdf7dd8e5c34f8037c402e2
# Google Analytics
google_track_id: 'UA-53994143-1'            # Format: UA-xxxxxx-xx
google_domain: auto

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tag
    class: fa fa-tags
    href: /tag.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /feed.xml