name: "Li's Station"
author: "li"
description: "Major in Finance, Quant, Data Science"
keyword: "liuli"
baseurl: ""
url: "https://liuli.blog" # liuli1735.github.io

plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed]

sass:
    sass_dir: assets/_sass
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
highlighter: rouge
permalink: /:title.html                 # /:year/:month/:day/:title.html
paginate: 5
excerpt_separator: "<!-- more -->"      # ReadMore separator

# SNS settings
#weibo_username:
#douban_username:
#zhihu_username:
#facebook_username: ll1735
#twitter_username: ll1735
#linkedin_username:
#github_username: liuli1735

# Disqus settings
disqus_username: liuli1735

# giscus settings
data-repo: liuli1735/liuli1735.github.io
data-repo-id: MDEwOlJlcG9zaXRvcnkyMTY0MjI4NQ==
data-category: Announcements
data-category-id: DIC_kwDOAUo8Lc4CPAch

# Analytics settings
# Baidu Analytics
baidu_track_id: 98dfb384afdf7dd8e5c34f8037c402e2
# Google Analytics
google_track_id: 'G-BRKM5JZ7G2'
